version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "practice-getting-started"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-4jsmpon17uu"
s3_prefix = "practice-getting-started"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
