AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Getting started practice app

Globals:
  Function:
    Timeout: 3

Resources:
  CounterTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions: 
        - AttributeName: id
          AttributeType: S
      KeySchema: 
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  GetHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: handlers/get/
      Handler: lambda.handler
      Runtime: nodejs12.x
      Environment:
        Variables:
          DDB_TABLE: !Ref CounterTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CounterTable
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /
            Method: get

Outputs:
  RootApi:
    Description: "API Gateway endpoint URL for Prod stage for Get function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  GetHandler:
    Description: "Get handler Lambda function ARN"
    Value: !GetAtt GetHandler.Arn
  GetHandlerIamRole:
    Description: "Implicit IAM Role created for Get handler"
    Value: !GetAtt GetHandlerRole.Arn
